### ISSUE TITLE
Chart won't show if using Chart.js versions beyond 2

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/js-weather-api-ajax#11]
Since in this lab we have to link to the Chart.js library ourselves, most people are going to grab the most recent version of Chart.js. However, the syntax for chart creation changed slightly and therefor unless version 1.1.1 or previous is used, we'll get an error in the console and the chart won't appear.

I've corrected the chart creation to reflect the 2+ syntax. See my pull request. #10

**Comment by AnnJohn** [comment]
thanks @NStephenson! merged the PR!
