### ISSUE TITLE
Specs seem to match older version of lab

### ISSUE THREAD

**Issue by RMcNeely** [learn-co-curriculum/js-weather-api-ajax#15]
Currently the Jasmine Specs in `spotify-chart.spec.js` seems to reflect and older version of the lesson.  It references two sets of data that should be charted while only having you extract one set of data with labels from the API. You do not need to make any adjustments to pass the tests, but this could lead to confusion when working on the lab. 

Also the comments containing the instructions tell you to query the first 20 tracks instead of 10.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by RMcNeely** [comment]
Woops it seems the direct link on Ask  A Question took me to the wrong lab, disregard this issue!
