### ISSUE TITLE
Chart not rendering in browser; tests passing

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/js-weather-api-ajax#18]
Closed out my other issue in learn-co-students because this belongs here. 

A student pointed out that the chart was not rendering, even though he had passed all tests for the lab. It seems the issue is related to the version of Chart.js and/or JQuery being used in the lab. Replacing the with JQuery and Chart.js scripts in index.html with the following seemed to fix this:

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js"></script>`

@aturkewi

**Comment by aturkewi** [comment]
Hey @cassaram09 thanks for posting this. 

I just took a look at the solution branch and it works fine with the version of chartjs and jquery that are in the vendor dir of the lab. The labs pass and the chart renders in browser. I simply added a note to the readme to ensure that students load from the vendor dir. 

Closing, but please re-open if I've misunderstood or missed something!
