### ISSUE TITLE
instructions not detailed enough

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/js-weather-api-ajax#5]
students had big questions on how the different pieces of their code fit together: what happens on document ready? what exactly is a callback function and how/when does it get invoked? what is chart.js and why do i need to pass it such a fancy and specific data structure?

Without giving away too much, I think we can outline the instructions better or provide an overview of how their code will work.

**Comment by cbdileo** [comment]
It is my understanding that these labs are to be completed after going through the JS coursework. Rehashing information they already learned seems redundant. I think that it could help to provide the function stubs like the [Spotify API Lab](https://github.com/learn-co-curriculum/js-spotify-api-ajax) would provide enough guidance.

**Comment by vicfriedman** [comment]
closing this issue after talking to @SophieDeBenedetto
