### ISSUE TITLE
spec doesn't pass with .done() syntax

### ISSUE THREAD

**Issue by NoneOfMaster** [learn-co-curriculum/js-weather-api-ajax#8]
The following passes the final test in the spec (line 27 of index_spec.rb):

```
function makeAjaxRequest(endpoint, success) {
    $.ajax({
        url: endpoint,
        dataType: 'jsonp',
        success: success
      });
    }
```

The following, which is what is used in the curriculum up until this point, and which seems functionally identical before what the spec is asking for, does not:

```
function makeAjaxRequest(endpoint, success) {
     $.ajax({
        url: endpoint,
        dataType: 'jsonp'
      }).done(success);
    }
```

**Comment by aturkewi** [comment]
It looks like this problem was solved. There is no longer an `index_spec.html` file and I'm not seeing this syntax in the spec anymore. 

Thanks for raising this issue! Looks like it's all set now :)
